### ISSUE TITLE
Pinouts and PCB

### ISSUE THREAD

**Issue by aleohl** [Creality3DPrinting/CR10-V2#4]
I need the pinout for the bed connector and the hotend. Can anyone find these?

**Comment by aleohl** [comment]
@sexycyborg any updates?

**Comment by aleohl** [comment]
Bump this issue. **~~So much for "open source" printer, right.~~**

**EDIT**: I stand corrected. I had the understanding that CR-10 v2 was open-source, but I was wrong. Thanks @sexycyborg for the clarification.

**Comment by MachineryEnchantress** [comment]
> Bump this issue. So much for "Open Source" printer, right.

The CR-10 is Open Source, the V2 is not. Nor it is advertised as such:
https://www.creality3dofficial.com/products/cr-10s-pro-v2-3d-printer

And since the community took to attacking me and demanding Creality defund me when I did fight for Open Source I don't anymore.

Play stupid games, win stupid prizes.
